Repository jrasell/chemtrail, pull requests merged in 2020-01, with the labels that each got.

#27 Fix panic when node is running an old version of the Nomad client.
  pkg/scale/resource/nodes.go
  pkg/scale/resource/nodes_test.go
Labels: area/autoscaling, kind/bug

#29 feat(doc/aws): add iam permissions
  docs/configuration/README.md
Labels: area/copy, kind/enhancement

#30 fix(doc): add missing consul argument
  docs/configuration/README.md
Labels: area/copy, kind/bug

#28 fix(cmd): add support for env var
  cmd/main.go
Labels: area/cli, kind/bug
